# Docker image workflow

name: Docker # ================================================================

on:
  push:
    branches: [ "main" ]
    tags: [ 'v*' ]
    paths:
      - ".github/workflows/docker.yml"
      - "docker/**"

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs: # =======================================================================

  # ---------------------------------------------------------------------------
  build-and-push-images: # create and publish Docker images
  # ---------------------------------------------------------------------------

    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v3
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}

      - name: Set an environment variable for the image tag
        id: tag-generator
        run: |
          echo "TAG=data" >> $GITHUB_ENV

      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: docker
          push: true
          tags: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ env.TAG }}
          labels: ${{ steps.meta.outputs.labels }}
